try{
	dir('a')
} catch(err){
	log('exception thrown '+err)
}
